name: Run terraform test Script

on:
  push:
    branches:
      - main
      - master

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          persist-credentials: false
          fetch-depth: 0

    - name: Run Script
      run: |
        chmod +x ./bash-test.sh
        ./bash-test.sh
